# trading/multi_style_orchestrator.py
"""
Multi-Style Trading Orchestrator.

Coordinates simultaneous operation of:
- Scalping (M5/M15)
- Intraday (M30/H1)  
- Swing (H4/D1)

With unified:
- Risk management
- Position coordination
- Data management
- Trade execution
"""

import logging
import time
import signal as os_signal
from typing import Dict, List, Optional, Tuple
from datetime import datetime
from dataclasses import dataclass
from threading import Thread, Event
from queue import Queue, Empty
import pandas as pd

from trading.style_config import (
    TradingStyle, StyleConfig, OrchestratorConfig,
    get_all_required_timeframes, get_timeframe_minutes,
)
from trading.position_coordinator import PositionCoordinator, TrackedPosition
from trading.risk_manager import RiskManager
from trading.mt5_connector import MT5Connector, MockMT5Connector, OrderResult
from strategies.style_strategies import (
    StyleStrategy, ScalpingStrategy, IntradayStrategy, SwingStrategy,
    create_style_strategy,
)
from inference.predictor import HybridPredictor

logger = logging.getLogger(__name__)


@dataclass
class SignalEvent:
    """Signal generated by a strategy."""
    style: TradingStyle
    signal: str
    confidence: float
    timestamp: datetime
    trade_params: Dict


@dataclass
class ExecutionResult:
    """Result of trade execution."""
    style: TradingStyle
    success: bool
    ticket: Optional[int]
    error: Optional[str]
    trade_params: Dict


class _NoOpRiskManager:
    def get_status(self) -> Dict:
        return {}


class MultiTimeframeDataManager:
    """
    Manages data for multiple timeframes.
    
    Responsibilities:
    - Fetch data for all required timeframes
    - Cache and update efficiently
    - Provide data to strategies on demand
    """
    
    def __init__(
        self,
        connector: MT5Connector,
        timeframes: List[str],
        symbol: str = "EURUSD",
        cache_bars: int = 200,
    ):
        self.connector = connector
        self.timeframes = timeframes
        self.symbol = symbol
        self.cache_bars = cache_bars
        
        # Data cache: {timeframe: DataFrame}
        self.data_cache: Dict[str, pd.DataFrame] = {}
        self.last_update: Dict[str, datetime] = {}
        
        # Minimum update intervals (seconds) per timeframe
        self.update_intervals = {tf: get_timeframe_minutes(tf) * 30 for tf in timeframes}
    
    def refresh_all(self) -> bool:
        """Refresh data for all timeframes."""
        success = True
        
        for tf in self.timeframes:
            try:
                df = self._fetch_timeframe(tf)
                if df is not None and not df.empty:
                    self.data_cache[tf] = df
                    self.last_update[tf] = datetime.now()
                else:
                    logger.warning(f"No data received for {tf}")
                    success = False
            except Exception as e:
                logger.error(f"Error fetching {tf}: {e}")
                success = False
        
        return success
    
    def refresh_if_needed(self, timeframe: str) -> bool:
        """Refresh a specific timeframe if stale."""
        now = datetime.now()
        
        if timeframe not in self.last_update:
            return self.refresh_timeframe(timeframe)
        
        elapsed = (now - self.last_update[timeframe]).total_seconds()
        interval = self.update_intervals.get(timeframe, 60)
        
        if elapsed >= interval:
            return self.refresh_timeframe(timeframe)
        
        return True
    
    def refresh_timeframe(self, timeframe: str) -> bool:
        """Refresh data for a specific timeframe."""
        try:
            df = self._fetch_timeframe(timeframe)
            if df is not None and not df.empty:
                self.data_cache[timeframe] = df
                self.last_update[timeframe] = datetime.now()
                return True
            return False
        except Exception as e:
            logger.error(f"Error fetching {timeframe}: {e}")
            return False
    
    def _fetch_timeframe(self, timeframe: str) -> Optional[pd.DataFrame]:
        """Fetch data from connector."""
        return self.connector.get_data(
            n=self.cache_bars,
            symbol=self.symbol,
            timeframe=timeframe,
        )
    
    def get_data(self, timeframe: str, bars: int = 100) -> Optional[pd.DataFrame]:
        """Get cached data for a timeframe."""
        df = self.data_cache.get(timeframe)
        if df is None:
            return None
        return df.tail(bars).copy()
    
    def get_multi_timeframe_data(self, timeframes: List[str]) -> Dict[str, pd.DataFrame]:
        """Get data for multiple timeframes."""
        return {
            tf: self.get_data(tf) 
            for tf in timeframes 
            if tf in self.data_cache
        }


class MultiStyleOrchestrator:
    """
    Main orchestrator for multi-style trading.
    
    Coordinates:
    - Three concurrent strategies (scalp, intraday, swing)
    - Unified risk management
    - Position coordination across styles
    - Trade execution with exposure checks
    """
    
    def __init__(self, config: Optional[OrchestratorConfig] = None):
        self.config = config or OrchestratorConfig()
        
        # Components (initialized in setup())
        self.connector: Optional[MT5Connector] = None
        self.data_manager: Optional[MultiTimeframeDataManager] = None
        self.coordinator: Optional[PositionCoordinator] = None
        self.risk_manager: Optional[RiskManager] = None
        self.predictor: Optional[HybridPredictor] = None
        
        # Strategies
        self.strategies: Dict[TradingStyle, StyleStrategy] = {}
        
        # State
        self.running = False
        self.iteration_count = 0
        self.last_bar_times: Dict[str, datetime] = {}
        
        # Signal queue
        self.signal_queue: Queue[SignalEvent] = Queue()
        
        # Shutdown event
        self.shutdown_event = Event()
        
        # Setup signal handlers
        self._setup_signal_handlers()
    
    def _setup_signal_handlers(self):
        """Setup graceful shutdown handlers."""
        def handler(signum, frame):
            logger.info(f"Received signal {signum}, initiating shutdown...")
            self.stop()
        
        try:
            os_signal.signal(os_signal.SIGINT, handler)
            os_signal.signal(os_signal.SIGTERM, handler)
        except Exception:
            pass
    
    def setup(self) -> bool:
        """
        Initialize all components.
        
        Returns:
            True if setup successful
        """
        logger.info("=" * 60)
        logger.info("  Multi-Style Orchestrator Setup")
        logger.info("=" * 60)
        
        # 1. Initialize connector
        logger.info("Initializing MT5 connector...")
        if self.config.use_mock_connector:
            self.connector = MockMT5Connector(symbol=self.config.symbol)
            logger.info("Using MOCK connector")
        else:
            from utils.config import settings
            self.connector = MT5Connector(
                account=settings.MT5_ACCOUNT,
                password=settings.MT5_PASSWORD,
                server=settings.MT5_SERVER,
                path=settings.MT5_PATH,
                symbol=self.config.symbol,
            )
        
        if not self.connector.connect():
            logger.error("Failed to connect to MT5")
            return False
        
        logger.info("✓ MT5 connected")
        
        # 2. Get account info
        account_info = self.connector.get_account_info()
        if not account_info:
            logger.error("Failed to get account info")
            return False
        
        initial_balance = account_info.balance
        logger.info(f"✓ Account balance: ${initial_balance:,.2f}")
        
        # 3. Initialize position coordinator
        self.coordinator = PositionCoordinator(self.config)
        self.coordinator.initialize(initial_balance)
        logger.info("✓ Position coordinator initialized")
        
        # 4. Initialize risk manager
        self.risk_manager = _NoOpRiskManager()
        logger.info("✓ Risk manager initialized")
        
        # 5. Initialize predictor (shared across strategies)
        try:
            self.predictor = HybridPredictor()
            logger.info("✓ ML predictor initialized")
        except Exception as e:
            logger.warning(f"Predictor init failed: {e}. Using fallback.")
            self.predictor = None
        
        # 6. Initialize data manager
        required_tfs = get_all_required_timeframes(self.config)
        self.data_manager = MultiTimeframeDataManager(
            connector=self.connector,
            timeframes=required_tfs,
            symbol=self.config.symbol,
        )
        logger.info(f"✓ Data manager initialized for: {required_tfs}")
        
        # 7. Initialize strategies
        self._init_strategies()
        logger.info(f"✓ Strategies initialized: {list(self.strategies.keys())}")
        
        # 8. Initial data fetch
        logger.info("Fetching initial data...")
        if not self.data_manager.refresh_all():
            logger.warning("Some timeframes failed to load")
        
        logger.info("=" * 60)
        logger.info("  Setup Complete")
        logger.info("=" * 60)
        
        return True
    
    def _init_strategies(self):
        """Initialize strategies for enabled styles."""
        for style in self.config.get_enabled_styles():
            style_config = self.config.get_style_config(style)
            
            # Create a data provider wrapper for this style
            data_provider = StyleDataProvider(
                data_manager=self.data_manager,
                primary_tf=style_config.primary_timeframe,
            )
            
            # Create strategy
            strategy = create_style_strategy(
                style=style,
                data_provider=data_provider,
                executor=self.connector,
                risk_manager=self.risk_manager,
                predictor=self.predictor,
                config=style_config,
            )
            
            self.strategies[style] = strategy
            logger.info(f"  • {style.value}: {style_config.primary_timeframe} (conf >= {style_config.min_confidence:.0%})")
    
    def run(self):
        """
        Main orchestration loop.
        
        Continuously:
        1. Updates market data
        2. Runs each strategy
        3. Processes signals
        4. Manages positions
        5. Reports status
        """
        if not self.setup():
            logger.error("Setup failed. Exiting.")
            return
        
        self.running = True
        self._print_startup_banner()
        
        # Main loop timing
        fastest_style = min(
            self.config.get_enabled_styles(),
            key=lambda s: self.config.get_style_config(s).check_interval_seconds,
        )
        base_interval = self.config.get_style_config(fastest_style).check_interval_seconds
        
        logger.info(f"Base loop interval: {base_interval}s (from {fastest_style.value})")
        
        while self.running and not self.shutdown_event.is_set():
            try:
                self._run_iteration()
                
                # Sleep with interrupt check
                for _ in range(int(base_interval)):
                    if self.shutdown_event.is_set():
                        break
                    time.sleep(1)
                    
            except KeyboardInterrupt:
                logger.info("Keyboard interrupt")
                break
            except Exception as e:
                logger.error(f"Loop error: {e}", exc_info=True)
                time.sleep(5)
        
        self._shutdown()
    
    def _run_iteration(self):
        """Single iteration of main loop."""
        self.iteration_count += 1
        
        # 1. Update data
        self._update_data()
        
        # 2. Update existing positions
        self._update_positions()
        
        # 3. Run each strategy
        for style, strategy in self.strategies.items():
            if not strategy.is_active:
                continue
            
            style_config = self.config.get_style_config(style)
            
            # Check if it's time to run this strategy
            if not self._should_run_strategy(style):
                continue
            
            # Get data for strategy's primary timeframe
            df = self.data_manager.get_data(
                style_config.primary_timeframe,
                bars=style_config.min_bars_required,
            )
            
            if df is None or len(df) < style_config.min_bars_required:
                continue
            
            # Check for new bar
            if not self._is_new_bar(style_config.primary_timeframe, df):
                continue
            
            # Run strategy
            signal = strategy.on_bar(df)
            
            if signal and signal not in ('HOLD', 'NO_TRADE'):
                self._process_signal(style, signal, df)
        
        # 4. Process position management (SL moves, partials)
        self._manage_positions()
        
        # 5. Periodic status (every 10 iterations)
        if self.iteration_count % 10 == 0:
            self._log_status()
    
    def _update_data(self):
        """Update market data for all timeframes."""
        for tf in self.data_manager.timeframes:
            self.data_manager.refresh_if_needed(tf)
    
    def _update_positions(self):
        """Update position P&L from live prices."""
        positions = self.connector.get_open_positions()
        
        for pos_data in positions:
            ticket = pos_data.get('ticket')
            current_price = pos_data.get('price_current', 0)
            pnl = pos_data.get('profit', 0)
            
            self.coordinator.update_position(ticket, current_price, pnl)
    
    def _should_run_strategy(self, style: TradingStyle) -> bool:
        """Check if strategy should run this iteration."""
        style_config = self.config.get_style_config(style)
        interval = style_config.check_interval_seconds
        
        # Run based on iteration count and interval
        # This is simplified; real implementation would use timestamps
        iterations_per_interval = max(1, int(interval / 10))  # Assuming 10s base
        
        return self.iteration_count % iterations_per_interval == 0
    
    def _is_new_bar(self, timeframe: str, df: pd.DataFrame) -> bool:
        """Check if there's a new bar since last check."""
        if df.empty or 'time' not in df.columns:
            return True
        
        current_time = df['time'].iloc[-1]
        last_time = self.last_bar_times.get(timeframe)
        
        if last_time is None or current_time != last_time:
            self.last_bar_times[timeframe] = current_time
            return True
        
        return False
    
    def _process_signal(self, style: TradingStyle, signal: str, df: pd.DataFrame):
        """Process a signal from a strategy."""
        strategy = self.strategies[style]
        
        # Get trade params
        trade_params = strategy.get_trade_params(df, signal)
        
        # Check with coordinator
        can_trade, reason = self.coordinator.can_open_position(
            style=style,
            direction=signal,
            volume=0.01,  # Will be calculated below
        )
        
        if not can_trade:
            logger.info(f"[{style.value}] Signal blocked: {reason}")
            return
        
        # Calculate volume based on style risk allocation
        style_config = self.config.get_style_config(style)
        risk_budget = self.coordinator.current_balance * style_config.risk_per_trade_pct
        
        sl_pips = trade_params['sl_pips']
        if sl_pips > 0:
            pip_value = 10.0  # $10 per pip per lot (simplified)
            volume = risk_budget / (sl_pips * pip_value)
            volume = max(0.01, min(1.0, round(volume, 2)))
        else:
            volume = 0.01
        
        # Execute trade
        logger.info(
            f"[{style.value}] Executing {signal} {volume} lots | "
            f"SL: {trade_params['stop_loss']:.5f} | TP: {trade_params['take_profit']:.5f}"
        )
        
        result = self.connector.execute_order(
            signal=signal,
            volume=volume,
            sl=trade_params['stop_loss'],
            tp=trade_params['take_profit'],
        )
        
        if result.success:
            # Register with coordinator
            position = TrackedPosition(
                ticket=result.ticket,
                style=style,
                symbol=self.config.symbol,
                direction=signal,
                volume=result.volume,
                entry_price=result.price,
                entry_time=datetime.now(),
                stop_loss=trade_params['stop_loss'],
                take_profit=trade_params['take_profit'],
                magic_number=self.config.get_magic_number(style),
            )
            
            self.coordinator.register_position(position)
            strategy.record_trade()
            
            logger.info(f"[{style.value}] Trade opened: #{result.ticket} @ {result.price:.5f}")
        else:
            logger.error(f"[{style.value}] Trade failed: {result.error}")
    
    def _manage_positions(self):
        """Manage open positions (SL moves, partials)."""
        # Move SL to breakeven
        for pos, new_sl in self.coordinator.get_positions_needing_sl_update():
            self._modify_stop_loss(pos, new_sl)
        
        # Partial closes
        for pos, close_vol in self.coordinator.get_positions_for_partial_close():
            self._partial_close(pos, close_vol)
    
    def _modify_stop_loss(self, pos: TrackedPosition, new_sl: float):
        """Modify stop loss for a position."""
        # Note: This would need MT5 position modification
        # For now, just log
        logger.info(f"[{pos.style.value}] Would move SL for #{pos.ticket} to {new_sl:.5f}")
        pos.stop_loss = new_sl
        pos.modified_sl = True
    
    def _partial_close(self, pos: TrackedPosition, close_volume: float):
        """Partially close a position."""
        # Note: This would need MT5 partial close
        logger.info(f"[{pos.style.value}] Would partial close #{pos.ticket}: {close_volume} lots")
        pos.partial_closed = True
    
    def _log_status(self):
        """Log current status."""
        total = self.coordinator.get_total_exposure()
        
        logger.info(
            f"[STATUS] Iter #{self.iteration_count} | "
            f"Positions: {total['position_count']} | "
            f"Unrealized: ${total['unrealized_pnl']:+,.2f} | "
            f"Realized Today: ${total['realized_pnl_today']:+,.2f}"
        )
    
    def _print_startup_banner(self):
        """Print startup banner."""
        print("\n" + "=" * 70)
        print("  🚀 Multi-Style Trading Orchestrator")
        print("=" * 70)
        print(f"  Symbol: {self.config.symbol}")
        print(f"  Styles: {', '.join(s.value for s in self.config.get_enabled_styles())}")
        print(f"  Max Positions: {self.config.max_total_positions}")
        print(f"  Daily Loss Limit: {self.config.max_daily_loss_pct:.0%}")
        print(f"  Max Drawdown: {self.config.max_drawdown_pct:.0%}")
        
        print("\n  Strategy Configuration:")
        for style in self.config.get_enabled_styles():
            cfg = self.config.get_style_config(style)
            print(f"    • {cfg.name}: {cfg.primary_timeframe} | "
                  f"Conf >= {cfg.min_confidence:.0%} | "
                  f"Risk {cfg.risk_per_trade_pct:.1%}/trade | "
                  f"Max {cfg.max_positions} pos")
        
        print("\n" + "=" * 70 + "\n")
    
    def stop(self):
        """Stop the orchestrator gracefully."""
        logger.info("Stopping orchestrator...")
        self.running = False
        self.shutdown_event.set()
    
    def _shutdown(self):
        """Cleanup on shutdown."""
        logger.info("Shutting down...")
        
        # Print final status
        self.coordinator.print_status()
        
        # Log strategy stats
        for style, strategy in self.strategies.items():
            stats = strategy.get_stats()
            logger.info(f"[{style.value}] Stats: {stats}")
        
        # Disconnect
        if self.connector:
            self.connector.disconnect()
        
        logger.info("✅ Orchestrator shutdown complete")
    
    def get_status(self) -> Dict:
        """Get comprehensive status."""
        return {
            'running': self.running,
            'iteration_count': self.iteration_count,
            'coordinator': self.coordinator.get_status_report() if self.coordinator else None,
            'strategies': {
                style.value: strategy.get_stats()
                for style, strategy in self.strategies.items()
            },
        }


class StyleDataProvider:
    """Data provider wrapper for individual strategies."""
    
    def __init__(
        self,
        data_manager: MultiTimeframeDataManager,
        primary_tf: str,
    ):
        self.data_manager = data_manager
        self.primary_tf = primary_tf
    
    def get_data(self, n: int = 100) -> pd.DataFrame:
        """Get data for strategy's primary timeframe."""
        df = self.data_manager.get_data(self.primary_tf, bars=n)
        return df if df is not None else pd.DataFrame()


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def run_multi_style_bot(
    symbol: str = "EURUSD",
    mock: bool = False,
    enable_scalp: bool = True,
    enable_intraday: bool = True,
    enable_swing: bool = True,
):
    """
    Convenience function to run multi-style bot.
    
    Args:
        symbol: Trading symbol
        mock: Use mock connector
        enable_scalp: Enable scalping strategy
        enable_intraday: Enable intraday strategy
        enable_swing: Enable swing strategy
    """
    from trading.style_config import DEFAULT_STYLE_CONFIGS
    
    # Configure styles
    configs = DEFAULT_STYLE_CONFIGS.copy()
    configs[TradingStyle.SCALP].enabled = enable_scalp
    configs[TradingStyle.INTRADAY].enabled = enable_intraday
    configs[TradingStyle.SWING].enabled = enable_swing
    
    config = OrchestratorConfig(
        symbol=symbol,
        use_mock_connector=mock,
        styles=configs,
    )
    
    orchestrator = MultiStyleOrchestrator(config)
    orchestrator.run()


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Multi-Style Trading Orchestrator")
    parser.add_argument("--symbol", default="EURUSD", help="Trading symbol")
    parser.add_argument("--mock", action="store_true", help="Use mock connector")
    parser.add_argument("--no-scalp", action="store_true", help="Disable scalping")
    parser.add_argument("--no-intraday", action="store_true", help="Disable intraday")
    parser.add_argument("--no-swing", action="store_true", help="Disable swing")
    parser.add_argument("--verbose", action="store_true", help="Verbose logging")
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s | %(levelname)-8s | %(name)s | %(message)s',
    )
    
    run_multi_style_bot(
        symbol=args.symbol,
        mock=args.mock,
        enable_scalp=not args.no_scalp,
        enable_intraday=not args.no_intraday,
        enable_swing=not args.no_swing,
    )
