MT5_ACCOUNT = 12345678
MT5_PASSWORD = "yourpassword"
MT5_SERVER = "Broker-ServerName"

SYMBOL = "EURUSD"
TIMEFRAME = "H1"
LOT_SIZE = 0.10

CONFIDENCE_THRESHOLD = 0.60

SL_ATR_MULTIPLIER = 0.5
TP_ATR_MULTIPLIER = 1.0

CHECK_INTERVAL = 60   # seconds
